### ISSUE TITLE
 Error creating bean with name 'nodeManager'

### ISSUE THREAD

**Issue by ShenEnQ** [tronprotocol/docker-tron-quickstart#18]
When i run `docker run -it -p 8091:8091 -p 8092:8092 -p 8090:8090 -p 50051:50051 -p 50052:50052 --rm --name tron trontools/quickstart:latest`.
The console is pending and did not generate 10 addresses.

`Start the http proxy for dApps...
nohup: appending output to 'nohup.out'
[HPM] Proxy created: /  ->  http://127.0.0.1:18190
[HPM] Proxy created: /  ->  http://127.0.0.1:18191
[HPM] Proxy created: /  ->  http://127.0.0.1:18891

 Full Node listening on http://127.0.0.1:8090
 Solidity Node listening on http://127.0.0.1:8091
 Event Server listening on http://127.0.0.1:8092
`

Then I got errors logs by ` docker exec -it tron tail -n 100  /tron/FullNode/logs/tron.log
` 
The details about the error:
`08:04:39.388 WARN  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:558) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/tron/FullNode/FullNode.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException
08:04:39.553 ERROR [main] [general](DefaultConfig.java:30) Uncaught exception
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/tron/FullNode/FullNode.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:732)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:197)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1267)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1124)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.tron.program.FullNode.main(FullNode.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1691)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:724)
        ... 13 common frames omitted
Caused by: java.lang.IllegalArgumentException: null
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1202)
        at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:89)
        at org.tron.core.db.Manager.init(Manager.java:381)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:309)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
        ... 26 common frames omitted
`
So, what is wrong?

**Comment by sullof** [comment]
Would you try the new version 1.2.0, please?

**Comment by ShenEnQ** [comment]
> Would you try the new version 1.2.2, please?

I tried version 1.2.2 and 1.2.3 but got the same error. From the error logs, I find this line:
`at org.tron.core.db.Manager.init(Manager.java:440)`
This class is in project java-tron. So I want to know, is it only me that I will encounter this error ？ Or the java-tron project  has an error?

**Comment by sullof** [comment]
That is very weird. Nobody else had the same issue.
Try the new version calling
```
docker run -it \
  -p 9090:9090 \
  -e "showQueryString=true" \
  -e "showBody=true" \
  -e "formatJson=true" \
  --name tron \
  trontools/quickstart:1.2.4
```

**Comment by kindex** [comment]
I got the same issue with quickstart 1.2.4.

**Comment by kindex** [comment]
Problem is in file https://github.com/tronprotocol/java-tron/blob/shasta-dev/src/main/java/org/tron/core/config/args/Args.java

    INSTANCE.validateSignThreadNum = config.hasPath("node.validateSignThreadNum") ? config
        .getInt("node.validateSignThreadNum") : Runtime.getRuntime().availableProcessors() / 2;

If you got only 1 processor, resulting value will be 0.

Just increase processor count to 2!

**Comment by sullof** [comment]
Thanks for that.
Try the new version 1.2.5. It is based on a different branch.

**Comment by sullof** [comment]
@UnforgivenZZZ can you take a look at that?

**Comment by JamesHutchison** [comment]
still seeing issue in SolidityNode logs with latest version

**Comment by JamesHutchison** [comment]
Stopping the VM, which by as installed by docker has 1 processor, and increasing it to 2 works around the issue

**Comment by sullof** [comment]
Thanks. We will ask the java-tron team to take a look at that. I will also add a note in the README.

**Comment by ShenEnQ** [comment]
> Stopping the VM, which as installed by docker has 1 processor, and increasing it to 2 works around the issue

Thanks a lot , it works.
